[package]
name = "bridge-runtime-common"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
repository = "https://github.com/paritytech/parity-bridges-common/"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
hash-db = { version = "0.15.2", default-features = false }
log = { version = "0.4.14", default-features = false }
num-traits = { version = "0.2", default-features = false }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
static_assertions = { version = "1.1", optional = true }

# Bridge dependencies

bp-messages = { path = "../../primitives/messages", default-features = false }
bp-parachains = { path = "../../primitives/parachains", default-features = false }
bp-polkadot-core = { path = "../../primitives/polkadot-core", default-features = false }
bp-runtime = { path = "../../primitives/runtime", default-features = false }
pallet-bridge-grandpa = { path = "../../modules/grandpa", default-features = false }
pallet-bridge-messages = { path = "../../modules/messages", default-features = false }
pallet-bridge-parachains = { path = "../../modules/parachains", default-features = false }

# Substrate dependencies

frame-support = { path = "../../../substrate-sora/frame/support", default-features = false }
frame-system = { path = "../../../substrate-sora/frame/system", default-features = false }
pallet-balances = { path = "../../../substrate-sora/frame/balances", default-features = false, optional = true }
pallet-transaction-payment = { path = "../../../substrate-sora/frame/transaction-payment", default-features = false }
sp-api = { path = "../../../substrate-sora/primitives/api", default-features = false }
sp-core = { path = "../../../substrate-sora/primitives/core", default-features = false }
sp-io = { path = "../../../substrate-sora/primitives/io", default-features = false }
sp-runtime = { path = "../../../substrate-sora/primitives/runtime", default-features = false }
sp-state-machine = { path = "../../../substrate-sora/primitives/state-machine", default-features = false, optional = true }
sp-std = { path = "../../../substrate-sora/primitives/std", default-features = false }
sp-trie = { path = "../../../substrate-sora/primitives/trie", default-features = false }
sp-version = { path = "../../../substrate-sora/primitives/version", default-features = false, optional = true }

# Polkadot dependencies

xcm = { git = "https://github.com/paritytech/polkadot", branch = "gav-xcm-v3", default-features = false }
xcm-builder = { git = "https://github.com/paritytech/polkadot", branch = "gav-xcm-v3", default-features = false }
xcm-executor = { git = "https://github.com/paritytech/polkadot", branch = "gav-xcm-v3", default-features = false }

[dev-dependencies]
millau-runtime = { path = "../millau/runtime" }

[features]
default = ["std"]
std = [
	"bp-messages/std",
	"bp-parachains/std",
	"bp-polkadot-core/std",
	"bp-runtime/std",
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"hash-db/std",
	"log/std",
	"num-traits/std",
	"pallet-bridge-grandpa/std",
	"pallet-bridge-messages/std",
	"pallet-bridge-parachains/std",
	"pallet-transaction-payment/std",
	"scale-info/std",
	"sp-api/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-state-machine/std",
	"sp-std/std",
	"sp-trie/std",
	"xcm/std",
	"xcm-builder/std",
	"xcm-executor/std",
]
runtime-benchmarks = [
	"pallet-balances",
	"pallet-bridge-grandpa/runtime-benchmarks",
	"pallet-bridge-messages/runtime-benchmarks",
	"sp-state-machine",
	"sp-version",
	"xcm-builder/runtime-benchmarks",
]
integrity-test = [
	"static_assertions",
]
